### ISSUE TITLE
nodenv/actions-node-version@v2.0.7 uses deprecated verison of ::add-path::

### ISSUE THREAD

**Issue by Pyrolistical** [nodenv/actions#13]
According to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

`::add-path::` is deprecated and needs to be converted to either use SDK api or use `$GITHUB_PATH`

See https://github.com/nodenv/actions/issues/13#issuecomment-742018324

~Looks like the fix is to upgrade `@actions/core` to 1.2.6 which is already done https://github.com/nodenv/actions/commit/8a7b195f56113779f4ece6bc3c3344366356ef93~

~We just need to cut a new release~

Error using it today

```
Run nodenv/actions-node-version@v2.0.7
  with:
    nodenv-version: 1.3.1
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/486819ad-7523-4bf8-afe4-2613328e2e39 -f /home/runner/work/_temp/b5e8c9bd-ef22-4217-ae4c-7cc185a3c2e4
Error: Unable to process command '::add-path::/opt/hostedtoolcache/nodenv/1.3.1/x64/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by StayClassic** [comment]
bump

**Comment by Pyrolistical** [comment]
@jasonkarns are you able to cut a release?

**Comment by asgeo1** [comment]
Hmm, I tried the latest commit from `master`, and it still failed:

```
name: My CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: nodenv/actions/node-version@104f741d7a447326be77c28fe4fff36758c3ac40
        id: nodenv
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'
      - run: npm run test
```

![image](https://user-images.githubusercontent.com/702212/101571871-fbf3dd80-3a2b-11eb-9486-475092165e5a.png)

I thought that would work. It said in the documentation you can use the monorepo directly

**Comment by Pyrolistical** [comment]
@asgeo1 I think i see the problem. According to the blogpost
> Action and workflow authors who are setting environment variables via STDOUT should update any usage of the set-env and add-path workflow commands to use the new environment files.

`::add-path::` is STDOUT and not the SDK method

**Comment by Pyrolistical** [comment]
@asgeo1 also, looking at the source. its very confusing. seems like the source uses the core addPath, but the dist still uses `::add-path::`. So do we just need to make a build?

**Comment by asgeo1** [comment]
Yeah that's right, it's using the `dist` version.  I realised that later.  So yeah it would need a new build published to resolve it.

But in the interim, you can also set the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable as a work around:

```
name: My CI

on: [push, pull_request]

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # only needed until next version of nodenv/actions/node-version is released
      - name: allow-unsecure-commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
        id: allow-unsecure-commands

      - uses: nodenv/actions/node-version@v2.0.7
        id: nodenv

      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'

      - run: npm install
      - run: npm run test
```

That works for me
